# Regenerates the bundled example data in inst/extdata/.
#
#   Rscript data-raw/example-data.R
#
# Run from the package root with the development version loaded. Keep the
# total size of inst/extdata/ at or below 2 MB. When the export schema changes,
# copy the previous inst/extdata/example-export/ to
# tests/testthat/fixtures/exports/<version>/ before regenerating.

devtools::load_all(".", quiet = TRUE)

extdata <- file.path("inst", "extdata")
dir.create(extdata, showWarnings = FALSE, recursive = TRUE)

# 1. Example slide: gk_simulate(seed = 1), written as a cellspec directory.
slide <- gk_simulate(n_cells = 8000L, seed = 1L, image_id = "example-01")
gk_write_cellspec(slide, file.path(extdata, "example-slide"), overwrite = TRUE)

# 2. Example configuration.
gk_write_config(gk_example_config(), file.path(extdata, "example-config.json"))

# 3. README with generator details.
writeLines(c(
  "gatekeepR example data",
  "======================",
  "",
  "Generated by data-raw/example-data.R. All data are simulated; no patient",
  "or study data are included.",
  "",
  "example-slide/        cellspec 1.0 directory from gk_simulate(n_cells = 8000, seed = 1)",
  "example-config.json   gk_write_config(gk_example_config())",
  "",
  paste0("gatekeepR version: ", as.character(utils::packageVersion("gatekeepR"))),
  paste0("cellspec specification: ", gatekeepR:::.gk_cellspec_version)
), file.path(extdata, "README"))

sizes <- file.info(list.files(extdata, recursive = TRUE, full.names = TRUE))$size
message(sprintf("inst/extdata total: %.2f MB", sum(sizes) / 1024^2))
