test_that("argument checks abort with gatekeepr_error_input and the user's argument name", {
  f <- function(value) .gk_check_string(value)
  expect_snapshot(f(1), error = TRUE)
  expect_error(.gk_check_string(""), class = "gatekeepr_error_input")
  expect_silent(.gk_check_string("", allow_empty = TRUE))
  expect_error(.gk_check_character(c("a", NA)), class = "gatekeepr_error_input")
  expect_error(.gk_check_character(character(), min_length = 1L), class = "gatekeepr_error_input")
  expect_error(.gk_check_character(c("a", "a"), unique = TRUE), class = "gatekeepr_error_input")
  expect_error(.gk_check_flag(NA), class = "gatekeepr_error_input")
  expect_error(.gk_check_number("1"), class = "gatekeepr_error_input")
  expect_error(.gk_check_number(2, max = 1), class = "gatekeepr_error_input")
  expect_silent(.gk_check_number(NA_real_, allow_na = TRUE))
  expect_identical(.gk_check_count(3), 3L)
  expect_error(.gk_check_count(1.5), class = "gatekeepr_error_input")
  expect_error(.gk_check_choice("x", c("a", "b")), class = "gatekeepr_error_input")
  expect_error(.gk_check_class(1, "gk_config"), class = "gatekeepr_error_input")
  expect_error(.gk_check_class(1, "gk_config", hint = "Use {.fn gk_config}."), "gk_config")
  expect_error(.gk_check_dir_exists(tempfile()), class = "gatekeepr_error_input")
  expect_error(.gk_check_file_exists(tempdir()), class = "gatekeepr_error_input")
})

test_that("reviewer IDs and reasons are safe to store in ledgers", {
  expect_silent(.gk_check_reviewer("reviewer-01"))
  expect_error(.gk_check_reviewer("a\tb"), class = "gatekeepr_error_input")
  expect_error(.gk_check_reviewer(strrep("x", 201)), class = "gatekeepr_error_input")
  expect_silent(.gk_check_reason("because"))
  expect_error(.gk_check_reason("   "), class = "gatekeepr_error_input")
  expect_silent(.gk_check_reason("", required = FALSE))
  expect_error(.gk_check_reason("a\nb"), class = "gatekeepr_error_input")
  expect_snapshot(.gk_check_reason(strrep("ä", 501)), error = TRUE)
})

test_that("missing suggested packages are listed together", {
  expect_silent(.gk_require("stats", "Plotting"))
  expect_snapshot(.gk_require(c("stats", "gk.no.such.pkg1", "gk.no.such.pkg2"), "The review app"), error = TRUE)
})

test_that("condition helpers attach parent and specific classes", {
  err <- tryCatch(.gk_abort("boom", class = "verify"), error = function(e) e)
  expect_s3_class(err, c("gatekeepr_error_verify", "gatekeepr_error"))
  expect_error(.gk_abort("boom", class = "nonsense"))
  expect_warning(.gk_warn("careful", class = "uncallable"), class = "gatekeepr_warning_uncallable")
  expect_identical(.gk_cli_escape("{a}"), "{{a}}")
})
