test_that("plot helpers return ggplot objects", {
  skip_if_not_installed("ggplot2")
  prep <- gk_example_prepared()
  cfg <- gk_example_config()
  th <- gk_thresholds(prep, cfg, seed = 1L)
  cl <- suppressWarnings(gk_classify(prep, th, cfg))
  st <- gk_state_calls(prep, th, cl, cfg)
  img <- unique(prep$cells$image_id)
  expect_s3_class(gk_plot_density(th, "PanCK", img), "ggplot")
  expect_s3_class(gk_plot_thresholds(th, img), "ggplot")
  expect_s3_class(gk_plot_density(st$state_thresholds, "FOXP3", img, "CD4 T cells"), "ggplot")
  expect_s3_class(gk_plot_dotplot(prep, cl, th), "ggplot")
  expect_s3_class(gk_plot_map(cl, img), "ggplot")
  expect_s3_class(gk_plot_states(st, img), "ggplot")
})

test_that("embedding plot and app use the public result contracts", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("uwot")
  skip_if_not_installed("shiny")
  prep <- gk_example_prepared()
  cfg <- gk_example_config()
  th <- gk_thresholds(prep, cfg, seed = 1L)
  cl <- suppressWarnings(gk_classify(prep, th, cfg))
  emb <- gk_embed(prep, n_pcs = 3L, grid = 30L, seed = 7L)
  expect_s3_class(gk_plot_embedding(emb, cl, "cell_type"), "ggplot")
  expect_invisible(print(emb))
  app <- gk_app(review = gk_example_review(), reviewer = "reviewer-01")
  expect_true(shiny::is.shiny.appobj(app))
  expect_true(shiny::is.shiny.appobj(gk_app()))
})
